/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
 */

public class Problem2{
    public static int iterativeAnswer(){
        int sum = 0;
        int fNumber = 1; // first number
        int sNumber = 2; // second number

        while (sNumber <= 4000000) {
            if (sNumber % 2 == 0) {  //find even Number
                sum = sum + sNumber;  //if True, + to sum
            }

            // ready the numbers for next step
            int temp = fNumber + sNumber; 
            fNumber = sNumber;
            sNumber = temp;
        }

        return sum;
    }


    public static void main(String[] args){
        System.out.println("Iterative Answer: "+ iterativeAnswer());
    }
}